name: Check JavaScript

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check-javascript:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm ci

      - name: Revisar JavaScript
        run: npm run check:js