name: Publicar la app

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pages: write

jobs:
  publicar:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./2doParcial/Clase19/contador

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: npm ci

      - name: Construir aplicación
        run: npm run build

      - name: Configurar Github Pages
        uses: actions/configure-pages@v5

      - name: Subir dist
        uses: actions/upload-pages-artifact@v4
        with:
          path: './2doParcial/Clase19/contador/dist'

      - name: Publicar
        uses: actions/deploy-pages@v4